# เปลี่ยนลิงก์เป็น URL ของ Repository ของคุณเอง
owner: testfunmorelife # ใส่ Username GitHub ของคุณ
repo: testfunmorelife.github.io      # ใส่ ชื่อ Repository ที่คุณตั้ง

# เพิ่มรายชื่อเว็บไซต์ที่ต้องการมอนิเตอร์ตรงนี้
sites:
  - name: Google Thailand
    url: https://google.co.th
  - name: bigoc
    url: https://huggingface.co/spaces/testunmorelife/bigoc # เปลี่ยนเป็นเว็บของคุณ
